global:
  imageTag: main
  environment: prod

backend:
  replicas: 2
  env:
    NODE_ENV: production
    LOG_LEVEL: warn
    DEMO_CANARY: "true"

frontend:
  replicas: 1

auth:
  replicas: 1

learning:
  replicas: 1

assessment:
  replicas: 1

ai-chat:
  replicas: 1

ai-worker:
  replicas: 1

ingress:
  host: "ai-tutot-ts.duckdns.org"
  clusterIssuer: "letsencrypt-prod"
  tls:
    enabled: true
    secretName: "ai-tutor-prod-tls"
